[features]
seeds = false
skip-lint = false
[programs.devnet]
breadheads = "BpBkYpEAd8vr4FynZE8g8Rrmwcr8BKS1Q8XFe7aL2tBL"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/work/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
