[features]
seeds = false
skip-lint = false
[programs.mainnet]
breadheads = "3i8fQhK9ZeTUPi83JpgShcAJ9M6UHJL8MCqGujr4czSW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
